
# This file was *autogenerated* from the file crypto_est.sage
from sage.all_cmdline import *   # import sage library

_sage_const_320 = Integer(320); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_342 = Integer(342); _sage_const_2 = Integer(2); _sage_const_0xFFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7EDEE386BFB5A899FA5AE9F24117C4B1FE649286651ECE65381FFFFFFFFFFFFFFFF = Integer(0xFFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7EDEE386BFB5A899FA5AE9F24117C4B1FE649286651ECE65381FFFFFFFFFFFFFFFF); _sage_const_10000 = Integer(10000); _sage_const_10 = Integer(10); _sage_const_113038384 = Integer(113038384)
import time

start = time.clock()

p = next_prime(_sage_const_0xFFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7EDEE386BFB5A899FA5AE9F24117C4B1FE649286651ECE65381FFFFFFFFFFFFFFFF )
R = Integers(p)
min_max_prime_factor = p
bestA = _sage_const_1 

myp = primes(_sage_const_10000 )
for power in range(_sage_const_320 ,_sage_const_342 ):        
	for i in range(_sage_const_0 , _sage_const_10 **power, _sage_const_10 **(power-_sage_const_3 )):                            
		A = _sage_const_113038384 *_sage_const_10 **power+i
		
		max_p = _sage_const_0 
		cur_R = (R(_sage_const_2 )**A).lift()
		for fac in myp:
			if cur_R % fac == _sage_const_0 :
				cur_R = cur_R // fac
				max_p = fac

		if cur_R.is_pseudoprime():
			if cur_R.is_prime():
				max_prime_factor = max(cur_R,max_p)

				if max_prime_factor < min_max_prime_factor:
					min_max_prime_factor = max_prime_factor
					bestA = A

print("A=", bestA)
print("2^A=", factor((R(_sage_const_2 )**bestA).lift()))
print(time.clock()-start)

