
# This file was *autogenerated* from the file sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1000000 = Integer(1000000); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_55 = Integer(55)
p = next_prime(_sage_const_1000000 )
R = Integers(p)
min_max_prime_factor = p

for p in range(_sage_const_1 ,_sage_const_5 ):        
	for i in range(_sage_const_10 **p):                            
		A = _sage_const_55 *_sage_const_10 **p+i
		max_prime_factor = (R(_sage_const_2 )**A).lift().factor()[-_sage_const_1 ][_sage_const_0 ]
		if max_prime_factor < min_max_prime_factor:
			min_max_prime_factor = max_prime_factor
			bestA = A

print(bestA)
 

